workflows:
  android-manual-build:
    name: Android Manual Build

    environment:
      java: 17
      android_signing:
        - infinity_keystore

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: '*'
          include: true
          source: true

    scripts:
      - name: Make gradlew executable
        script: chmod +x ./gradlew

      - name: Build release APK
        script: |
          ./gradlew assembleRelease
          
          echo "Build version: $(grep "versionName" app/build.gradle | awk '{print $2}' | tr -d '\"')"
          echo "Build code: $(grep "versionCode" app/build.gradle | awk '{print $2}')"

    artifacts:
      - app/build/outputs/**/*.apk
      - app/build/outputs/**/mapping.txt
